apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-nlb-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{NLB_PUBLIC_DNS}}
    secretName: tls-secret

  rules:
  - host: {{NLB_PUBLIC_DNS}}
    http:
      paths:
      - path: /echo-hostname
        backend:
          serviceName: hostname-service
          servicePort: 80
