apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hostname-deployment
  labels:
    app: hostname-service-label

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostname-service-label

  template:
    metadata:
      labels:
        app: hostname-service-label

    spec:
      containers:
        - name: hostname-service-container
          image: alicek106/ingress-annotation-test:print-proxy-origin-ip
          ports:
          - name: flask-port
            containerPort: 5000
          imagePullPolicy: Always
